### ISSUE TITLE
Error using CopyFromHDFS

### ISSUE THREAD

**Issue by pacorodrgz** [Esri/geoprocessing-tools-for-hadoop#11]
Hi all,

I'm having troubles when importing JSON table from HDFS to ArcMap 10.3 (English language package).

The table is succesfully generated from earthquake.csv file from sample by:

CREATE TABLE agg_samp(point binary)
ROW FORMAT SERDE 'com.esri.hadoop.hive.serde.JsonSerde'              
STORED AS INPUTFORMAT 'com.esri.json.hadoop.UnenclosedJsonInputFormat'
OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat';
INSERT OVERWRITE TABLE agg_samp SELECT ST_Point(latitude, longitude) FROM earthquakes_new;

and it looks like this:
![tabla](https://cloud.githubusercontent.com/assets/12309506/7657027/f7c6a5e0-fb2e-11e4-99c0-70f7a6a1e462.JPG)

When importing it by the set up:
![copyfromhdfs](https://cloud.githubusercontent.com/assets/12309506/7657081/78702b62-fb2f-11e4-8c39-c6952c5f1aa0.JPG)

I get the following error:
![error](https://cloud.githubusercontent.com/assets/12309506/7657088/87ff8f8c-fb2f-11e4-8b3c-33d6249a0d13.JPG)

I already checked Issue #22 but couldn't find a solution.

Can you, please, help me?

Thanks in advance.

**Comment by pacorodrgz** [comment]
Ok, solved by adding first "/" in HDFS path:

"/apps/hive/warehouse/agg_samp"

**Comment by pacorodrgz** [comment]
CopyFromHDFS definetly works. How ever, importing JSON file into ArcMap from a local path I get an error because of JSON file format:

"Error parsing json file. Unexpected '{'; state : endOfObject; buffer : }

May it be an issue with the query statement?

Could you please help me?

Thank you.

**Comment by climbage** [comment]
Can you make sure you are setting it to unenclosed json?

**Comment by pacorodrgz** [comment]
Unenclosed JSON worked for the script to impor the file (Woops). However, points seem to be mirrored and in vertical layout.
![jsontofeature](https://cloud.githubusercontent.com/assets/12309506/7658370/ce44c1ce-fb39-11e4-93f3-d5cf8f6cba1c.JPG)

**Comment by climbage** [comment]
Cool - `ST_Point(latitude, longitude)` should be `ST_Point(longitude, latitude)` since longitude is on the x axis.

**Comment by pacorodrgz** [comment]
That's right. Thank you so much for your help!
