### ISSUE TITLE
esri hive JSON serde not found

### ISSUE THREAD

**Issue by geoHeil** [Esri/geoprocessing-tools-for-hadoop#22]
Following along in spark at https://github.com/geoHeil/spatial-heatmaps/tree/master/esri
the JSON serde is not found 
`ClassNotFoundException: Class com.esri.hadoop.hive.serde.JsonSerde not found
`
even though:
```
"com.esri.hadoop" % "spatial-sdk-hive" % esriVersion,
 "com.esri.hadoop" % "spatial-sdk-json" % esriVersion,
```
i.e. the current master branch (2.1.0-SNAPSHOT) are on the class path. Am I missing a dependency? The base JSON Serde would be available but is not called.

The issue here probably makes more sense than at https://github.com/Esri/gis-tools-for-hadoop/issues/65

**Comment by geoHeil** [comment]
It looks like JsoonSerde is obsolete? https://github.com/Esri/spatial-framework-for-hadoop/search?utf8=✓&q=JsonSerde&type= but apparently still used from the current master branch.

**Comment by randallwhitman** [comment]
The one to pursue is https://github.com/Esri/gis-tools-for-hadoop/issues/66
